In [53]:
import pandas as pd
import numpy as np

In [5]:
dataMod = pd.read_csv('resultsMod.csv')
dataOr = pd.read_csv('resultsOriginal.csv')

In [64]:
dataMod

,targetsDetected,destroyed,whereDestroyed.x,missionSuccess,decisionTimeAvg,decisionTimeVar
0,0,0,39,0,0.014355,0.000293
1,1,0,39,0,0.013260,0.000179
2,2,0,39,1,0.013835,0.000203
3,0,0,39,0,0.012565,0.000163
4,0,0,39,0,0.012475,0.000159
5,1,0,39,0,0.012600,0.000163
6,2,0,39,1,0.012347,0.000157
7,0,0,39,0,0.012955,0.000171
8,0,0,39,0,0.013797,0.000204
9,0,0,39,0,0.012785,0.000168
10,1,1,38,0,0.012595,0.000161
11,1,1,34,0,0.011897,0.000144
12,0,1,13,0,0.012086,0.000152
13,0,0,39,0,0.012563,0.000162
14,1,0,39,0,0.013547,0.000270
15,2,0,39,1,0.015050,0.000572
16,1,0,39,0,0.013410,0.000210
17,3,0,39,1,0.012165,0.000156
18,1,0,39,0,0.019050,0.000459
19,1,0,39,0,0.011865,0.000148
20,1,1,28,0,0.012528,0.000168
21,0,0,39,0,0.011890,0.000158
22,0,0,39,0,0.013050,0.000202
23,0,0,39,0,0.011750,0.000162
24,0,0,39,0,0.011980,0.000160
25,1,0,39,0,0.102660,0.307430
26,1,0,39,0,0.013647,0.000297
27,0,0,39,0,0.012435,0.000224
28,0,0,39,0,0.012410,0.000214
29,1,0,39,0,0.015305,0.000457
...,...,...,...,...,...,...
99970,3,0,39,1,0.009612,0.000134
99971,1,1,39,0,0.008595,0.000103
99972,1,1,24,0,0.008996,0.000126
99973,0,0,39,0,0.008803,0.000121
99974,1,0,39,0,0.008950,0.000121
99975,0,0,39,0,0.009367,0.000141
99976,0,0,39,0,0.009685,0.000148
99977,0,0,39,0,0.008632,0.000106
99978,1,1,18,0,0.008316,0.000100
99979,0,0,39,0,0.008327,0.000077
99980,0,1,5,0,0.011100,0.000211
99981,1,1,29,0,0.014367,0.000303
99982,0,0,39,0,0.013585,0.000279
99983,0,0,39,0,0.009920,0.000173
99984,0,0,39,0,0.015443,0.000379
99985,0,0,39,0,0.012730,0.000257
99986,1,0,39,0,0.013032,0.000268
99987,1,1,36,0,0.008478,0.000107
99988,1,0,39,0,0.007497,0.000075
99989,0,0,39,0,0.007122,0.000053
99990,1,0,39,0,0.006763,0.000046
99991,1,0,39,0,0.006972,0.000050
99992,0,0,39,0,0.007110,0.000052
99993,0,1,28,0,0.009755,0.000135
99994,0,1,19,0,0.009315,0.000115
99995,1,0,39,0,0.008578,0.000105
99996,1,0,39,0,0.009940,0.000147
99997,1,1,19,0,0.009790,0.000147
99998,1,1,27,0,0.009418,0.000131
99999,0,1,13,0,0.010386,0.000181

In [65]:
dataOr

,targetsDetected,destroyed,whereDestroyed.x,missionSuccess,decisionTimeAvg,decisionTimeVar
0,1,0,39,0,0.016168,0.000464
1,1,0,39,0,0.016250,0.000438
2,1,0,39,0,0.017707,0.000461
3,0,0,39,0,0.021442,0.000710
4,1,0,39,0,0.023383,0.000850
5,0,1,9,0,0.022240,0.000622
6,2,0,39,1,0.020690,0.000575
7,2,0,39,1,0.020057,0.000535
8,0,0,39,0,0.019992,0.000524
9,1,0,39,0,0.022982,0.000680
10,1,0,39,0,0.020473,0.000656
11,2,0,39,1,0.020997,0.000584
12,1,0,39,0,0.018605,0.000481
13,0,0,39,0,0.019220,0.000487
14,1,0,39,0,0.019975,0.000522
15,1,0,39,0,0.018052,0.000426
16,0,0,39,0,0.019000,0.000489
17,2,0,39,1,0.021538,0.000715
18,1,0,39,0,0.020390,0.000549
19,2,0,39,1,0.019157,0.000506
20,1,0,39,0,0.018322,0.000441
21,0,0,39,0,0.018892,0.000473
22,1,0,39,0,0.018898,0.000491
23,3,0,39,1,0.023355,0.000886
24,2,0,39,1,0.021965,0.000644
25,0,1,18,0,0.016084,0.000325
26,1,0,39,0,0.013028,0.000176
27,2,0,39,1,0.011022,0.000127
28,1,0,39,0,0.011657,0.000145
29,0,0,39,0,0.017913,0.000434
...,...,...,...,...,...,...
99970,1,0,39,0,0.012558,0.000166
99971,2,0,39,1,0.013282,0.000223
99972,0,0,39,0,0.012462,0.000166
99973,2,0,39,1,0.013530,0.000209
99974,1,0,39,0,0.013553,0.000203
99975,1,0,39,0,0.012822,0.000174
99976,3,0,39,1,0.012507,0.000168
99977,0,0,39,0,0.073183,0.130466
99978,1,0,39,0,0.015193,0.000296
99979,0,0,39,0,0.013775,0.000214
99980,1,0,39,0,0.014580,0.000247
99981,0,0,39,0,0.014640,0.000279
99982,0,0,39,0,0.012680,0.000194
99983,2,0,39,1,0.012403,0.000175
99984,0,0,39,0,0.013528,0.000225
99985,0,0,39,0,0.011692,0.000152
99986,0,0,39,0,0.014903,0.000268
99987,0,0,39,0,0.013853,0.000231
99988,1,0,39,0,0.014943,0.000271
99989,1,0,39,0,0.013048,0.000214
99990,1,0,39,0,0.013707,0.000227
99991,2,0,39,1,0.014190,0.000235
99992,2,0,39,1,0.014893,0.000245
99993,0,0,39,0,0.015848,0.000494
99994,0,0,39,0,0.014480,0.000270
99995,1,0,39,0,0.013243,0.000185
99996,0,0,39,0,0.013103,0.000217
99997,1,0,39,0,0.012937,0.000177
99998,0,0,39,0,0.012200,0.000161
99999,1,0,39,0,0.012408,0.000177

# original Stats

###  Success rate

In [93]:
successCounts = np.unique(np.array(dataOr.iloc[:,3:4]),return_counts=True)
print( "Success rate: ", successCounts[1][1]/(successCounts[1][1]+successCounts[1][0]))

Success rate:  0.26827

### Destroyed Rate

In [94]:
destroyedCounts = np.unique(np.array(dataOr.iloc[:,1:2]),return_counts=True)
print( "Destroyed rate: ", destroyedCounts[1][1]/(destroyedCounts[1][1]+destroyedCounts[1][0]))

Destroyed rate:  0.02683

### Decision TimeAvg Stats

In [89]:
dataOr.iloc[:,4:5].describe()

        decisionTimeAvg
count     100000.000000
mean           0.017355
std            0.024615
min           -0.818802
25%            0.010600
50%            0.013845
75%            0.019480
max            1.474530

### Decision Time variance Stats

In [90]:
dataOr.iloc[:,5:6].describe()

        decisionTimeVar
count     100000.000000
mean           0.022259
std            0.722692
min            0.000041
25%            0.000159
50%            0.000278
75%            0.000589
max           84.201700

# Stats for random values between 0-5

### Success Rate

In [96]:
modSuccessCounts = np.unique(np.array(dataMod.iloc[:,3:4]),return_counts=True)
print( "Success rate: ", modSuccessCounts[1][1]/(modSuccessCounts[1][1]+modSuccessCounts[1][0]))

Success rate:  0.12586

### Destroyed Rate

In [97]:
modDestroyedCounts = np.unique(np.array(dataMod.iloc[:,1:2]),return_counts=True)
print( "Destroyed rate: ", modDestroyedCounts[1][1]/(modDestroyedCounts[1][1]+modDestroyedCounts[1][0]))

Destroyed rate:  0.16095

### Decision TimeAvg Stats

In [98]:
dataMod.iloc[:,4:5].describe()

        decisionTimeAvg
count     100000.000000
mean           0.017259
std            0.032467
min           -1.207580
25%            0.011458
50%            0.014742
75%            0.019184
max            3.546280

### Decision Time variance Stats

In [99]:
dataMod.iloc[:,5:6].describe()

        decisionTimeVar
count     100000.000000
mean           0.032374
std            1.150742
min            0.000035
25%            0.000195
50%            0.000349
75%            0.000565
max          162.706000

### Observations

##### These results are based on 100,000 simulations of the dartsim adaption manager. 
##### For random simulation of random latencies, the value was limited to 5 periods. The defualt value for latency is 1 period.
##### The most visible differences between the two sets of simulations are the success and destroyed rate. Having random values for latencies negatively affects the performance of the adaption manager.

##### Latency = 1 vs. Latency = (random)
##### Success rate = 0.26827 vs. 0.12586
##### Destroyed rate = 0.02683 vs. 0.16095